/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportsclub;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Login
 */
public class admin_new extends javax.swing.JInternalFrame {

    /**
     * Creates new form admin_new
     */
    public admin_new() {
        initComponents();
        set_re.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tf_answer = new javax.swing.JTextField();
        tf_name = new javax.swing.JTextField();
        tf_uname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        bt_create = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bt_back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmb_sq = new javax.swing.JComboBox();
        tf_pswd = new javax.swing.JPasswordField();
        tf_re_pswd = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        lbl_re_enter = new javax.swing.JLabel();
        set_re = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 102), 3, true), "New Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(0, 204, 0))); // NOI18N

        tf_answer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf_answer.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tf_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tf_uname.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf_uname.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Name");

        bt_create.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_create.setText("Create");
        bt_create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_createActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Your Password");

        bt_back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_back.setText("Back");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Answer");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Username");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Your Security Question");

        cmb_sq.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmb_sq.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "What is Your Name...?", "Why You Come here...?", "What You Want...?", "What is Your Problem...?" }));
        cmb_sq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_sqActionPerformed(evt);
            }
        });

        tf_re_pswd.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                tf_re_pswdCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                tf_re_pswdInputMethodTextChanged(evt);
            }
        });
        tf_re_pswd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_re_pswdActionPerformed(evt);
            }
        });
        tf_re_pswd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tf_re_pswdKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_re_pswdKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_re_pswdKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Re-Your Password");

        lbl_re_enter.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        lbl_re_enter.setForeground(new java.awt.Color(255, 51, 51));
        lbl_re_enter.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        set_re.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        set_re.setForeground(new java.awt.Color(255, 0, 0));
        set_re.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        set_re.setText("retype password doesn't match...!!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(bt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(bt_create, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(lbl_re_enter, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(119, 119, 119)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_name)
                            .addComponent(tf_uname)
                            .addComponent(tf_answer)
                            .addComponent(cmb_sq, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tf_pswd)
                            .addComponent(tf_re_pswd)
                            .addComponent(set_re, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmb_sq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(tf_answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(tf_pswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_re_pswd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_re_enter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(37, 37, 37))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(set_re, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_back)
                    .addComponent(bt_create))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_createActionPerformed
        if(idget()<=3){
            if((tf_name.getText().trim().isEmpty()) || (tf_uname.getText().trim().isEmpty()) || (tf_answer.getText().trim().isEmpty()) || (tf_pswd.getText().trim().isEmpty() || (tf_re_pswd.getText().trim().isEmpty()))){
                JOptionPane.showMessageDialog(null,"all fields are recquired...");
            }
            else {
                String p1,p2;
                p1=tf_pswd.getText();
                p2=tf_re_pswd.getText();
                if(p1.equals(p2)){

                    try{
                        DBConnection c=new DBConnection();
                        try (Connection con = c.newDBConnection()) {
                            System.out.println("connection established");
                            PreparedStatement stmt=con.prepareStatement("insert into admin(slno,name,uname,pswd,sq,answer) values(?,?,?,?,?,?)");
                            System.out.println("statement created");
                            stmt.setInt(1, idget());
                            stmt.setString(2, tf_name.getText()) ;
                            stmt.setString(3, tf_uname.getText()) ;
                            String pass = new String(tf_pswd.getPassword());
                            stmt.setString(4, pass) ;
                            stmt.setString(5, (String) cmb_sq.getSelectedItem()) ;
                            stmt.setString(6, tf_answer.getText()) ;
                            System.out.println("statement created");
                            int res=stmt.executeUpdate();
                            if(res>=1)
                            JOptionPane.showMessageDialog(null, "Account Created Successfully...");
                            else
                            JOptionPane.showMessageDialog(null, "Something went Wrong...");
                            con.close();
                            //this.setVisible(false);
                        }
                    }
                    catch(Exception e){
                        JOptionPane.showMessageDialog(null,e);
                    }

                }
                else{
                    JOptionPane.showMessageDialog(null,"Retyped Password is Different...");
                }

                // else{

                    //}
            }}
            else{
                JOptionPane.showMessageDialog(null,"maximum Number of accounts reached.!.!.!");
            }
    }//GEN-LAST:event_bt_createActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_backActionPerformed

    private void cmb_sqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_sqActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_sqActionPerformed

    private void tf_re_pswdCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tf_re_pswdCaretPositionChanged

    }//GEN-LAST:event_tf_re_pswdCaretPositionChanged

    private void tf_re_pswdInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_tf_re_pswdInputMethodTextChanged

    }//GEN-LAST:event_tf_re_pswdInputMethodTextChanged

    private void tf_re_pswdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_re_pswdActionPerformed

    }//GEN-LAST:event_tf_re_pswdActionPerformed

    private void tf_re_pswdKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_re_pswdKeyPressed

    }//GEN-LAST:event_tf_re_pswdKeyPressed

    private void tf_re_pswdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_re_pswdKeyTyped

    }//GEN-LAST:event_tf_re_pswdKeyTyped

    private void tf_re_pswdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_re_pswdKeyReleased
        if(tf_re_pswd.getText().equals(tf_pswd.getText())){
            set_re.setVisible(false);
        }else{
            set_re.setVisible(true);
        }
    }//GEN-LAST:event_tf_re_pswdKeyReleased
private int idget(){
        int newid=0;
        try{
            DBConnection c=new DBConnection();
            Connection con=c.newDBConnection();
            System.out.println("connection established");
            Statement stmt = con.createStatement();
            ResultSet rs= stmt.executeQuery("select slno from admin");
            while (rs.next()){
                newid=rs.getInt(1);
                System.out.println(newid);
            }
            if(newid==0)
                newid=1;
            else
                newid++;
        con.close();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
            return newid;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_create;
    private javax.swing.JComboBox cmb_sq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_re_enter;
    private javax.swing.JLabel set_re;
    private javax.swing.JTextField tf_answer;
    private javax.swing.JTextField tf_name;
    private javax.swing.JPasswordField tf_pswd;
    private javax.swing.JPasswordField tf_re_pswd;
    private javax.swing.JTextField tf_uname;
    // End of variables declaration//GEN-END:variables
}
