/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportsclub;

import java.sql.Connection;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDate;
import java.time.Period;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Login
 */
public class category extends javax.swing.JInternalFrame {

    DefaultTableModel dt =new DefaultTableModel();
    //String sprt;
    
    public category() {
        initComponents();
    }
    public void setData(String str){
        fillTable(str);
        jLabel1.setText(str+" "+jLabel1.getText());
    }
    private int findAge(String a){
    String dob[] = a.split("-") ;
    int year = Integer.parseInt(dob[0]);
    int month = Integer.parseInt(dob[1]);
    int day = Integer.parseInt(dob[2]);
    
    LocalDate selectedDate = LocalDate.of(year,month,day);
    LocalDate currentDate = LocalDate.now();
    int resultYear = Period.between(selectedDate, currentDate).getYears();
    
    return resultYear;
}
    
    
    
public void fillTable(String sprt){
    
        ArrayList<MemberList> al=null;
        al=new ArrayList<MemberList>();
        try{
            DBConnection c=new DBConnection();
            Connection con=c.newDBConnection();
            System.out.println("Connection Established for cataegory");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from members where sports like '%"+sprt+"%'");
            MemberList list;
        
            
            while(rs.next()){
                list =new MemberList(rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6));
                al.add(list);
            }
            dt = (DefaultTableModel) member_list.getModel();
            dt.setRowCount(0);
            Object[] row = new Object[6];
            int j=1;
            for (int i = 0; i <al.size(); i++) {
                row[0]=j;
                row[1]=al.get(i).getId();
                row[2]=al.get(i).getName();
                row[3]=al.get(i).getPhone();
                row[4]=findAge(al.get(i).getDob());
                row[5]=al.get(i).getBg();
                j++;
                dt.addRow(row);
        
            }
        }catch(Exception e){
            System.out.println(e);
        }
}
        
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        member_list = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(819, 590));
        setVerifyInputWhenFocusTarget(false);

        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("X");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Aharoni", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Team");

        member_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SL.NO", "ID", "Name", "Phone", "Age", "BloodGroup"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        member_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                member_listMouseClicked(evt);
            }
        });
        member_list.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                member_listKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(member_list);
        if (member_list.getColumnModel().getColumnCount() > 0) {
            member_list.getColumnModel().getColumn(0).setResizable(false);
            member_list.getColumnModel().getColumn(0).setPreferredWidth(5);
            member_list.getColumnModel().getColumn(1).setResizable(false);
            member_list.getColumnModel().getColumn(1).setPreferredWidth(5);
            member_list.getColumnModel().getColumn(2).setResizable(false);
            member_list.getColumnModel().getColumn(2).setPreferredWidth(125);
            member_list.getColumnModel().getColumn(3).setResizable(false);
            member_list.getColumnModel().getColumn(3).setPreferredWidth(70);
            member_list.getColumnModel().getColumn(4).setResizable(false);
            member_list.getColumnModel().getColumn(4).setPreferredWidth(50);
            member_list.getColumnModel().getColumn(5).setResizable(false);
            member_list.getColumnModel().getColumn(5).setPreferredWidth(50);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(70, 70, 70))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void member_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_member_listMouseClicked
        // TODO add your handling code here:
        //int ind = member_list.getSelectedRow();
       // showItemToTable(ind);
    }//GEN-LAST:event_member_listMouseClicked

    private void member_listKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_member_listKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_member_listKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable member_list;
    // End of variables declaration//GEN-END:variables
}
