/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportsclub;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Faris
 */
public class events extends javax.swing.JInternalFrame {

    DefaultTableModel dt = new DefaultTableModel();
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    int add = 1;
    String id = null;

    public events() {
        initComponents();
        fillTable();
        bt_cancel.setVisible(false);
    }

    public void fillTable() {
        ArrayList<MemberList> al = loadData();
        dt = (DefaultTableModel) event_list.getModel();
        dt.setRowCount(0);
        Object[] row = new Object[5];
        int j = 1;
        for (int i = 0; i < al.size(); i++) {
            row[0] = j;
            row[1] = al.get(i).getId();
            row[2] = al.get(i).getCtgry();
            row[3] = al.get(i).getDate();
            row[4] = al.get(i).getLastDate();
            j++;
            dt.addRow(row);

        }

    }

    public ArrayList<MemberList> loadData() {
        ArrayList<MemberList> al = null;
        al = new ArrayList<MemberList>();
        try {
            DBConnection c = new DBConnection();
            Connection con = c.newDBConnection();
            System.out.println("Connection Established");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select * from event");
            MemberList list;
            while (rs.next()) {
                list = new MemberList(rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4));
                al.add(list);
            }

        } catch (Exception e) {
            System.out.println("Error in Retrive Data : " + e);

        }
        return al;
    }

    public void showItemToFields (int index) throws ParseException{
        id = event_list.getModel().getValueAt(index, 1).toString();
        dc_date.setDate(sdf.parse(event_list.getModel().getValueAt(index, 3).toString()));
        dc_ldate.setDate(sdf.parse(event_list.getModel().getValueAt(index, 4).toString()));
        String sports = event_list.getModel().getValueAt(index, 2).toString();
        if(sports.contains("Cri")){
            cmb_ctry.setSelectedIndex(0);
        }
        else if(sports.contains("Foot")){
            cmb_ctry.setSelectedIndex(1);
        }
        else if(sports.contains("Voll")){
            cmb_ctry.setSelectedIndex(2);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        event_list = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dc_date = new com.toedter.calendar.JDateChooser();
        dc_ldate = new com.toedter.calendar.JDateChooser();
        cmb_ctry = new javax.swing.JComboBox();
        bt_add_edit = new javax.swing.JButton();
        bt_delete = new javax.swing.JButton();
        bt_cancel = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Events");

        event_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SL.NO", "Event_id", "Catagory", "Date", "LastDate"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        event_list.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                event_listMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(event_list);
        if (event_list.getColumnModel().getColumnCount() > 0) {
            event_list.getColumnModel().getColumn(0).setResizable(false);
            event_list.getColumnModel().getColumn(0).setPreferredWidth(10);
            event_list.getColumnModel().getColumn(1).setResizable(false);
            event_list.getColumnModel().getColumn(1).setPreferredWidth(10);
            event_list.getColumnModel().getColumn(2).setResizable(false);
            event_list.getColumnModel().getColumn(2).setPreferredWidth(30);
            event_list.getColumnModel().getColumn(3).setResizable(false);
            event_list.getColumnModel().getColumn(3).setPreferredWidth(25);
            event_list.getColumnModel().getColumn(4).setResizable(false);
            event_list.getColumnModel().getColumn(4).setPreferredWidth(25);
        }

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Add / Edit / Delete an Event");

        jLabel3.setText("Category");

        jLabel4.setText("Date");

        jLabel5.setText("LastDate");

        cmb_ctry.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cricket", "FootBall", "VolleyBall" }));

        bt_add_edit.setText("Add");
        bt_add_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_add_editActionPerformed(evt);
            }
        });

        bt_delete.setText("Delete");

        bt_cancel.setText("Cancel");
        bt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dc_date, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(dc_ldate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_ctry, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bt_cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_delete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bt_add_edit)))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(cmb_ctry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(dc_date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(53, 53, 53)
                                .addComponent(jLabel5))
                            .addComponent(dc_ldate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_add_edit)
                            .addComponent(bt_delete)
                            .addComponent(bt_cancel))
                        .addGap(39, 39, 39))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_add_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_add_editActionPerformed
        
       if(add == 0){
           
       }
       else if(add == 1){
           
       }
        
        
    }//GEN-LAST:event_bt_add_editActionPerformed

    private void event_listMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_event_listMouseClicked
       add = 0;
       bt_add_edit.setText("Edit");
       bt_cancel.setVisible(true);
       int ind = event_list.getSelectedRow();
        try {
            showItemToFields(ind);
        } catch (ParseException ex) {
            Logger.getLogger(events.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_event_listMouseClicked

    private void bt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelActionPerformed
        bt_add_edit.setText("Add");
        cmb_ctry.setSelectedIndex(0);
        dc_date.setDate(null);
        dc_ldate.setDate(null);
        bt_cancel.setVisible(false);
    }//GEN-LAST:event_bt_cancelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add_edit;
    private javax.swing.JButton bt_cancel;
    private javax.swing.JButton bt_delete;
    private javax.swing.JComboBox cmb_ctry;
    private com.toedter.calendar.JDateChooser dc_date;
    private com.toedter.calendar.JDateChooser dc_ldate;
    private javax.swing.JTable event_list;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
