/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportsclub;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Login
 */
public class forgtpsw extends javax.swing.JInternalFrame {
    
    ResultSet rs;
    /**
     * Creates new form forgtpsw
     */
    public forgtpsw() {
        initComponents();
        ldl_warning.setVisible(false);
    }
    private void Search(){
        DBConnection c=new DBConnection();
        Connection con=c.newDBConnection();
        System.out.println("Connection Established");
        if((tf_uname1.getText().trim().isEmpty())){
            ldl_warning.setVisible(true);
        }
        else{
        String a1 = tf_uname1.getText();
        String sql = "select * from admin where uname='"+a1+"'";
        try{
        Statement stmt = con.createStatement();
        ResultSet rs = stmt.executeQuery(sql);
            if(rs.next()){
                ldl_warning.setVisible(false);
                tf_name.setText(rs.getString(2));
                tf_ysq.setText(rs.getString(5));
                rs.close();
            }
            else{
                JOptionPane.showMessageDialog(null,"Incorrect UserName...");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        }
    }
    private void Retrive(){
        String a1 = tf_uname1.getText();
        String a2 = tf_answer.getText();
        String sql = "select * from admin where uname='"+a1+"' and answer='"+a2+"'";
        try{
            DBConnection c=new DBConnection();
            Connection con=c.newDBConnection();
            PreparedStatement stmt=con.prepareStatement(sql);
            ResultSet rs = stmt.executeQuery();
            if(rs.next()){
                tf_pswd1.setText(rs.getString(4));
            }
            else{
                JOptionPane.showMessageDialog(null,"Answer invalied...");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_forget = new javax.swing.JPanel();
        tf_answer = new javax.swing.JTextField();
        tf_name = new javax.swing.JTextField();
        bt_search = new javax.swing.JButton();
        tf_uname1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        bt_retrive = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        bt_back = new javax.swing.JButton();
        tf_pswd1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_ysq = new javax.swing.JTextField();
        ldl_warning = new javax.swing.JLabel();

        panel_forget.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 102), 3, true), "Forgot Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(255, 0, 0))); // NOI18N

        tf_answer.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf_answer.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        tf_name.setEditable(false);
        tf_name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf_name.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        bt_search.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_search.setText("Search");
        bt_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_searchActionPerformed(evt);
            }
        });

        tf_uname1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf_uname1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Name");

        bt_retrive.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_retrive.setText("Retrive");
        bt_retrive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_retriveActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("Your Password");

        bt_back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_back.setText("Back");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        tf_pswd1.setEditable(false);
        tf_pswd1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf_pswd1.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Answer");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Username");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Your Security Question");

        tf_ysq.setEditable(false);
        tf_ysq.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tf_ysq.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        ldl_warning.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        ldl_warning.setForeground(new java.awt.Color(255, 0, 0));
        ldl_warning.setText("* this field is must");

        javax.swing.GroupLayout panel_forgetLayout = new javax.swing.GroupLayout(panel_forget);
        panel_forget.setLayout(panel_forgetLayout);
        panel_forgetLayout.setHorizontalGroup(
            panel_forgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_forgetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_forgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_forgetLayout.createSequentialGroup()
                        .addGroup(panel_forgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_forgetLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panel_forgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panel_forgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_forgetLayout.createSequentialGroup()
                                .addGroup(panel_forgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(tf_uname1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(tf_answer, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tf_name))
                                .addGap(18, 18, 18)
                                .addGroup(panel_forgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(bt_retrive, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(bt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(tf_ysq, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ldl_warning, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_forgetLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_pswd1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        panel_forgetLayout.setVerticalGroup(
            panel_forgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_forgetLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_forgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tf_uname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_search))
                .addGap(2, 2, 2)
                .addComponent(ldl_warning, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_forgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(panel_forgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(tf_ysq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_forgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(panel_forgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_answer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_retrive)))
                .addGap(18, 18, 18)
                .addGroup(panel_forgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(panel_forgetLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_pswd1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bt_back)))
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_forget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_forget, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_searchActionPerformed
        Search();
    }//GEN-LAST:event_bt_searchActionPerformed

    private void bt_retriveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_retriveActionPerformed
        Retrive();
    }//GEN-LAST:event_bt_retriveActionPerformed

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_backActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_back;
    private javax.swing.JButton bt_retrive;
    private javax.swing.JButton bt_search;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel ldl_warning;
    private javax.swing.JPanel panel_forget;
    private javax.swing.JTextField tf_answer;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_pswd1;
    private javax.swing.JTextField tf_uname1;
    private javax.swing.JTextField tf_ysq;
    // End of variables declaration//GEN-END:variables
}
