/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sportsclub;

import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.*;
import java.util.Date;

/**
 *
 * @author Login
 */
public class newMember extends javax.swing.JInternalFrame {

    String ids = null;
    String tabl = null;

    /**
     * Creates new form newMember
     */
    public newMember() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_name = new javax.swing.JTextField();
        tf_phoneno = new javax.swing.JTextField();
        cmb_bg = new javax.swing.JComboBox();
        bt_add = new javax.swing.JButton();
        bt_back = new javax.swing.JButton();
        dt_chsr = new com.toedter.calendar.JDateChooser();
        cb_fb = new javax.swing.JCheckBox();
        cb_c = new javax.swing.JCheckBox();
        cb_vb = new javax.swing.JCheckBox();
        jlbl_av = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 255, 204), 3, true), jlbl_av.getText(), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 18), new java.awt.Color(51, 255, 204))); // NOI18N

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Blood Group");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Phone NO");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("D O B");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Sports Item");

        cmb_bg.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A+", "B+", "AB+", "O+", "A-", "B-", "AB-", "O-" }));

        bt_add.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        bt_add.setText("ADD");
        bt_add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_addActionPerformed(evt);
            }
        });

        bt_back.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_back.setText("Cancel");
        bt_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_backActionPerformed(evt);
            }
        });

        cb_fb.setText("FootBall");

        cb_c.setText("Cricket");

        cb_vb.setText("VolleyBall");
        cb_vb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_vbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmb_bg, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dt_chsr, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cb_fb, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_c, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cb_vb, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(bt_back, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(163, 163, 163)
                .addComponent(bt_add, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 3, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(dt_chsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tf_phoneno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_fb)
                        .addComponent(cb_c)
                        .addComponent(cb_vb)))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmb_bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_add)
                    .addComponent(bt_back))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addComponent(jlbl_av, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jlbl_av))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_backActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_backActionPerformed

    private void cb_vbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_vbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_vbActionPerformed

    private void bt_addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_addActionPerformed
        
        if (jlbl_av.getText().trim().equals("AddNewMember")) {
            tabl = "members";
            ids = "M-";
        } else if (jlbl_av.getText().trim().equals("Suggest_A_Member")) {
            tabl = "visitors";
            ids = "V-";
        }
        if ((tf_name.getText().trim().isEmpty()) || (tf_phoneno.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(null, "all fields are recquired...");
        } else {

            try {
                DBConnection c = new DBConnection();
                try (Connection con = c.newDBConnection()) {
                    System.out.println("connection established");
                    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
                    String date = sdf.format(dt_chsr.getDate());
                    PreparedStatement stmt = con.prepareStatement("insert into " + tabl + "(id,name,phone,dob,bg,sports) values(?,?,?,?,?,?)");
                    System.out.println("statement created");
                    stmt.setString(1, idget());
                    stmt.setString(2, tf_name.getText());
                    stmt.setString(3, tf_phoneno.getText());
                    stmt.setString(4, (date));
                    stmt.setString(5, (String) cmb_bg.getSelectedItem());
                    String sports = null;
                    if (cb_fb.isSelected()) {
                        if (sports == null) {
                            sports = "FootBall";
                        } else {
                            sports = sports + "FootBall";
                        }
                    }
                    if (cb_c.isSelected()) {
                        if (sports == null) {
                            sports = "Cricket";
                        } else {
                            sports = sports + ",Cricket";
                        }
                    }
                    if (cb_vb.isSelected()) {
                        if (sports == null) {
                            sports = "VolleyBall";
                        } else {
                            sports = sports + ",VolleyBall";
                        }
                    }
                    stmt.setString(6, sports);
                    System.out.println("statement created");
                    int res = stmt.executeUpdate();
                    if (res >= 1) {
                        JOptionPane.showMessageDialog(null, "Member Added Successfully...");
                        try {

                            String sql = "select * from admin where active=1";
                            PreparedStatement un = con.prepareStatement(sql);
                            ResultSet rs = un.executeQuery(sql);
                            String uname = "";
                            if (rs.next()) {
                                uname = rs.getString(3);
                            }
                            PreparedStatement pst = con.prepareStatement("insert into history values(?,?,?,?)");
                            pst.setString(1, uname);
                            pst.setString(2, tf_name.getText());
                            Date today = new Date();
                            pst.setString(3, sdf.format(today));
                            pst.setString(4, "Added");
                            System.out.println("statement created");
                            int history = pst.executeUpdate();
                            con.close();
                            //this.setVisible(false);
                        } catch (Exception e) {
                            JOptionPane.showMessageDialog(null, e);
                        }
                            //tf_name.setText("");
                        //dt_chsr.setDate("");
                    } else {
                        JOptionPane.showMessageDialog(null, "Something went Wrong...");
                    }
                    con.close();
                    this.dispose();
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }

    }//GEN-LAST:event_bt_addActionPerformed
    private String idget() {
        int newid = 0;
        try {
            DBConnection c = new DBConnection();
            Connection con = c.newDBConnection();
            System.out.println("connection established");
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select id from '"+tabl+"'");
            while (rs.next()) {
                String id[] = rs.getString(1).split("-");
                newid = Integer.parseInt(id[1]);;
            }
            if (newid == 0) {
                newid = 1;
            } else {
                newid++;
            }
            con.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        return ids + newid;
    }

    public void setAV(String a) {
        jlbl_av.setText(a);
        jlbl_av.setVisible(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_add;
    private javax.swing.JButton bt_back;
    private javax.swing.JCheckBox cb_c;
    private javax.swing.JCheckBox cb_fb;
    private javax.swing.JCheckBox cb_vb;
    private javax.swing.JComboBox cmb_bg;
    private com.toedter.calendar.JDateChooser dt_chsr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbl_av;
    private javax.swing.JTextField tf_name;
    private javax.swing.JTextField tf_phoneno;
    // End of variables declaration//GEN-END:variables
}
